services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    hostname: kafka
    ports:
      - "29092:29092"   # host access
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1

      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data

  cockroach-1:
    image: cockroachdb/cockroach:v23.1.11 #specific version, just tom ake sure there are no problems in future.
    hostname: cockroach-1
    container_name: roach-1
    command: >
      start --insecure
      --listen-addr=:26257              
      --advertise-addr=cockroach-1:26257   
      --http-addr=0.0.0.0:8080            
      --join=cockroach-1,cockroach-2,cockroach-3
      --store=/cockroach/cockroach-data
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - crdb1:/cockroach/cockroach-data

  cockroach-2:
    image: cockroachdb/cockroach:v23.1.11
    hostname: cockroach-2
    container_name: roach-2
    command: >
      start --insecure
      --listen-addr=:26257
      --advertise-addr=cockroach-2:26257
      --http-addr=0.0.0.0:8080
      --join=cockroach-1,cockroach-2,cockroach-3
      --store=/cockroach/cockroach-data
    volumes:
      - crdb2:/cockroach/cockroach-data

  cockroach-3:
    image: cockroachdb/cockroach:v23.1.11
    hostname: cockroach-3
    container_name: roach-3
    command: >
      start --insecure
      --listen-addr=:26257
      --advertise-addr=cockroach-3:26257
      --http-addr=0.0.0.0:8080
      --join=cockroach-1,cockroach-2,cockroach-3
      --store=/cockroach/cockroach-data
    volumes:
      - crdb3:/cockroach/cockroach-data

  flyway:
    image: flyway/flyway:10
    depends_on:
      - cockroach-1
    volumes:
      - ./code/migrations:/flyway/sql:ro
    command: >
      -url=jdbc:postgresql://cockroach-1:26257/defaultdb
      -user=root
      -password=
      -connectRetries=60
      migrate
      
  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - cockroach-1


  producer-a:
    build: ./code2/producer
    volumes:
      - ./data:/data:ro
    environment:
      TENANT_TOPIC: tenant-a-bronze
    depends_on:
      - cockroach-1

  producer-b:
    build: ./code2/producer
    volumes:
      - ./data:/data:ro
    environment:
      TENANT_TOPIC: tenant-b-bronze
    depends_on:
      - cockroach-1

  tenant-a-worker:
    build: ./code2/tenants/tenant-a
    environment:
      - TENANT_ID=tenant-a
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    depends_on:
      - cockroach-1

  stream-ingest-manager:
    build: ./code2/stream-ingest-manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    environment:
      - TENANT_ID=tenant-a
      - REPLICAS=3

  tenant-b-worker:
    build: ./code2/tenants/tenant-b
    environment:
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
      - TENANT_ID=tenant-b
    depends_on:
      - cockroach-1

  ingest-1:
    build: ./code/ingest
    environment:
      - WORKER_ID=0
      - WORKERS=10
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    volumes:
      - ./data:/data:ro
    depends_on:
      - cockroach-1

  ingest-2:
    build: ./code/ingest
    environment:
      - WORKER_ID=1
      - WORKERS=10
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    volumes:
      - ./data:/data:ro
    depends_on:
      - cockroach-1

  ingest-3:
    build: ./code/ingest
    environment:
      - WORKER_ID=2
      - WORKERS=10
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    volumes:
      - ./data:/data:ro
    depends_on:
      - cockroach-1

  ingest-4:
    build: ./code/ingest
    environment:
      - WORKER_ID=3
      - WORKERS=10
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    volumes:
      - ./data:/data:ro
    depends_on:
      - cockroach-1

  ingest-5:
    build: ./code/ingest
    environment:
      - WORKER_ID=4
      - WORKERS=10
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    volumes:
      - ./data:/data:ro
    depends_on:
      - cockroach-1

  ingest-6:
    build: ./code/ingest
    environment:
      - WORKER_ID=5
      - WORKERS=10
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    volumes:
      - ./data:/data:ro
    depends_on:
      - cockroach-1

  ingest-7:
    build: ./code/ingest
    environment:
      - WORKER_ID=6
      - WORKERS=10
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    volumes:
      - ./data:/data:ro
    depends_on:
      - cockroach-1

  ingest-8:
    build: ./code/ingest
    environment:
      - WORKER_ID=7
      - WORKERS=10
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    volumes:
      - ./data:/data:ro
    depends_on:
      - cockroach-1

  ingest-9:
    build: ./code/ingest
    environment:
      - WORKER_ID=8
      - WORKERS=10
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    volumes:
      - ./data:/data:ro
    depends_on:
      - cockroach-1

  ingest-10:
    build: ./code/ingest
    environment:
      - WORKER_ID=9
      - WORKERS=10
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    volumes:
      - ./data:/data:ro
    depends_on:
      - cockroach-1

  consumer-1:
    build: ./code/consumer
    environment:
      - WORKER_ID=1
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    depends_on:
      - cockroach-1

  consumer-2:
    build: ./code/consumer
    environment:
      - WORKER_ID=2
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    depends_on:
      - cockroach-1

  consumer-3:
    build: ./code/consumer
    environment:
      - WORKER_ID=3
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    depends_on:
      - cockroach-1

  consumer-4:
    build: ./code/consumer
    environment:
      - WORKER_ID=4
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    depends_on:
      - cockroach-1

  consumer-5:
    build: ./code/consumer
    environment:
      - WORKER_ID=5
      - DATABASE_URL=postgresql://root@cockroach-1:26257/reddit?sslmode=disable
    depends_on:
      - cockroach-1

volumes:
  crdb1:
  crdb2:
  crdb3:
  kafka_data: